# Gary Koplik
# January, 2018
# use_xml_parser.R

# clear old code for replicability
rm(list = ls())

# load libraries -- install them if needed
library(lubridate)
library(dplyr)

######################################################
# MAKE THE DATASET - ENTER THE 5 VALUES BELOW
######################################################

### NOTE, this code is currently set to take the 5 resulting user inputs that save
#   when running get_user_input.py
#   but there is sufficient information below to hard code them in yourself
###


# set to run based on user_inputs.csv generated by running get_user_input
args <- read.csv("./user_input.csv", header = F)

# Enter the Following 3 Values
# securityName is the name of the security you want
# NOTE this must follow exact notation below
# example value left here for you to change
securityName = as.character(args[1, 1]) # CHANGE this if hand coding values

# TIPS auction or not
# if you want a TIPS auction, say "Y"
# if you do not want TIPS, say "N"
TIPS = as.character(args[1, 2]) # CHANGE this if hand coding values

# FRN auction or not
# if you want a FRN auction, say "Y"
# if you do not want FRN, say "N"
FRN = as.character(args[1, 3]) # CHANGE this if hand coding values

# convert date range to posixct
date_min <- mdy(args[1, 4]) # CHANGE this if hand coding values
date_max <- mdy(args[1, 5]) # CHANGE this if hand coding values

# NOTE: the actualSecurity must be specified in a specific way:
#   CMB:             "0-WEEK"
#   4-week T-bills:  "4-WEEK"
#   13-week T-bills: "13-WEEK"
#   26-week T-bills: "26-WEEK"
#   52-week T-bills: "52-WEEK"
#   2-year notes:    "2-YEAR"
#   3-year notes:    "3-YEAR"
#   5-year notes:    "5-YEAR"
#   7-year notes:    "7-YEAR"
#   10-year notes:   "10-YEAR"
#   30-year bonds:   "30-YEAR"

############################################################
# DO NOT CHANGE CODE BELOW UNLESS YOU KNOW WHAT YOU'RE DOING
############################################################


# read in functions to download and parse xml
source("get_xml.r")

# if the python script doesn't run, you can go to this website:
# https://www.treasurydirect.gov/instit/annceresult/annceresult_query.htm
#   filtered on your security of interest
#   (and make sure you download at least the date range you want)
#   then save to csv
#     which defaults to Securities.csv

# all you need to do is make sure Securities.csv is in the SAME folder as this file


dates <- read.csv("./Securities.csv") %>%
  select(Auction.Date) %>%
  mutate(date = mdy(Auction.Date)) %>%
  filter(date >= date_min) %>%
  filter(date <= date_max) %>%
  select(date)

auctions <- makeTable(dates,
                      actualSecurity = securityName,
                      TIPS = TIPS, FRN = FRN)


write.csv(auctions[1], file = paste0("./auction_", securityName,"_tips_",
                                     TIPS, "_frn_", FRN, ".csv"), row.names = F)
write.csv(auctions[2], file = paste0("./failed_dates_", securityName,"_tips_",
                                     TIPS, "_frn_", FRN, ".csv"), row.names = F)

